# Deploy to Azure Kubernetes Service
# Build and push image to Azure Container Registry; Deploy to Azure Kubernetes Service
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master


variables:

  # Container registry service connection established during pipeline creation
  buildConfiguration: 'Release'
  tag: '$(Build.BuildNumber)'
  imageRepository: 'bytheappdemo-api'
  # dockerRegistryServiceConnection: '80d4c17a-3be2-4b84-aa86-b5e6c9bbc991'
  # containerRegistry: 'pngoacr.azurecr.io'
  # dockerfilePath: '**/Dockerfile'
  # imagePullSecret: 'pngoacr5fe2-auth'

stages:
  - stage: Build
    displayName: 'Build project'
    jobs:
      - job: Build
        displayName: Build
        pool:
          vmImage: ubuntu-latest
        
        steps:
        
        - task: UsePythonVersion@0
          inputs:
            versionSpec: '3.x'
            addToPath: true
            architecture: 'x64'
          displayName: 'Install python version 3.x'
        
        - script: |
            pip install --upgrade pip
            pip install -r requirements.txt
          displayName: 'Install dependencies'
        
        - script: |
          displayName: 'Build project'
          
  - stage: DeployDev
    displayName: 'Deploy dev'
    dependsOn: Build
    condition: and(succeeded(), eq(variables['build.sourceBranch'], 'refs/heads/master'))
    
    variables:
      - group: bytheapp-demo
      - name: repository-image
        value: 'bytheapp.azurecr.io/bytheappdemo-api:$(Build.BuildNumber)'
      - name: acr-secret-name
        value: 'by-the-app-acr-secret'
      - name: host-url
        value: 'api-demo.bytheapp.com'
      - name: env-name
        value: 'Production'
      - name: env-namespace
        value: 'by-the-app-prod'
    jobs:
      - job: DeployApp
        displayName: 'Deploy web api'
        pool:
          vmImage: 'ubuntu-latest'
        steps:
          - task: Docker@2
            inputs:
              containerRegistry: 'containerRegistry'
              repository: '$(imageRepository)'
              command: 'buildAndPush'
              Dockerfile: '**/Dockerfile'
              buildContext: .
              tags: |
                $(tag)

          - task: CopyFiles@2
            inputs:
              SourceFolder: '$(System.DefaultWorkingDirectory)/manifests'
              Contents: 'deployment.yml'
              TargetFolder: '$(Build.ArtifactStagingDirectory)/manifests'
          
          - task: qetza.replacetokens.replacetokens-task.replacetokens@3
            displayName: 'Replace tokens in deploy file'
            inputs:
              rootDirectory: '$(Build.ArtifactStagingDirectory)/manifests'
              targetFiles: 'deployment.yml'
              escapeType: none
              
          - script: 'cat $(Build.ArtifactStagingDirectory)/manifests/deployment.yml'
            displayName: 'Cat deploy'
            
          - task: KubectlInstaller@0
            inputs:
              kubectlVersion: 'latest'

          - task: Kubernetes@1
            inputs:
              connectionType: 'Kubernetes Service Connection'
              kubernetesServiceEndpoint: 'by-the-app-cluster'
              namespace: by-the-app-prod'
              command: 'apply'
              arguments: '-f $(Build.ArtifactStagingDirectory)/manifests/deployment.yml'
              secretType: 'dockerRegistry'
              containerRegistryType: 'Container Registry'
              dockerRegistryEndpoint: 'containerRegistry'
              secretName: 'by-the-app-acr-secret1'

       

